class InternalError(Exception):
    pass


class ResourceBrokenError(Exception):
    pass

